say("Hello World, This is a really big text so the scroll can work correctly without any problem")
say("Let's talk about a real good thing t t t t t t t t t")
say("Let's talk about a real good thing t t t t t t t t t")
say("Let's talk about a real good thing t t t t t t t t t")
say("Let's talk about a real good thing t t t t t t t t t")
